Fixed long options and added more verbocity

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,5 +1,6 @@
 #!/bin/bash
 VERSION="0.1"
+ROOT="$(dirname "$0")"
 SELF="$(basename "$0")"
 
 
@@ -48,10 +49,8 @@ function help() {
   options
 }
 
-declare -A config
-default_dir=""
-
 function parse_config() {
+  default_value=""
   while IFS= read -r line
   do
     # Trim leading/trailing whitespace using Bash parameter expansion
@@ -71,11 +70,72 @@ function parse_config() {
     value="${value%"${value##*[![:space:]]}"}"
 
     if [[ "$key" == "." ]]; then
-      default_dir="$value"
-    else
-      config["$key"]="$value"
+      default_value="$value"
+    elif [[ "$2" == "$key" ]]; then
+      echo "$value"
+      return 0
     fi
   done < "$1/$CONFIG_FILE_PATH"
+
+  echo "$default_value"
+}
+
+function symlink_directory() {
+  local SOURCE="$1"
+  local TARGET="$2"
+  local IGNORE="$3"
+  local DEFER="$4"
+  local OVERRIDE="$5"
+  local ADOPT="$6"
+  local DOTFILES="$7"
+  local COMPAT="$8"
+  local SIMULATE="$9"
+  local VERBOSE="${10}"
+
+  if [ -d "$TARGET" ]; then
+    for directory in $(ls -a $SOURCE)
+    do
+      if [[ "$directory" == "." || "$directory" == ".." ]]; then
+        continue
+      fi
+
+      symlink_directory "$SOURCE/$directory" "$TARGET/$directory" "$IGNORE" "$DEFER" "$OVERRIDE" "$ADOPT" "$DOTFILES" "$COMPAT" "$SIMULATE" "$VERBOSE"
+    done
+  else
+    if [[ "$SIMULATE" == "1" ]]; then
+      if [ "$VERBOSE" -ge 1 ]; then
+        echo "LINK: $SOURCE => $TARGET"
+      fi
+      return 0
+    fi
+
+
+    result=$(ln -s "$SOURCE" "$TARGET" 2>&1)
+    status=$?
+
+    if [[ $status -eq 1 ]]; then
+      if [[ "$result" == "*Permission denied*" ]]; then
+        echo "Permission denied: Command found but not executable"
+        sudo -E ln -s "$SOURCE" "$TARGET"
+        if [[ $? -eq 0 ]]; then
+          if [ "$VERBOSE" -ge 1 ]; then
+            echo "LINK: $SOURCE => $TARGET"
+          fi
+        fi
+      fi
+    #elif [[ $status -eq 127 ]]; then
+      #echo "Command not found"
+    #elif [[ $status -ne 0 ]]; then
+      #echo "Command failed with exit code $status"
+    #else
+      #echo "Command succeeded"
+    else
+      echo "is 0 $VERBOSE"
+      if [ "$VERBOSE" -ge 1 ]; then
+        echo "LINK: $SOURCE => $TARGET"
+      fi
+    fi
+  fi
 }
 
 function stow() {
@@ -93,10 +153,21 @@ function stow() {
 
   echo "$PACKAGE, $DIR, $TARGET, $IGNORE, $DEFER, $OVERRIDE, $ADOPT, $DOTFILES, $COMPAT, $SIMULATE, $VERBOSE"
 
-  echo $(parse_config $DIR)
 
   if [ -d "$DIR/$PACKAGE" ]; then
-    echo "$DIR/$PACKAGE"
+    for directory in $DIR/$PACKAGE/*/ $DIR/$PACKAGE/.[^.]*
+    do
+      targ="$(parse_config $DIR $(basename "$directory") | envsubst)"
+
+      symlink_directory "$directory" "$targ" "$IGNORE" "$DEFER" "$OVERRIDE" "$ADOPT" "$DOTFILES" "$COMPAT" "$SIMULATE" "$VERBOSE"
+
+
+      #ln -s "$directory" "$targ"
+      
+    done
+  else
+    echo "dotman: ERROR: The stow directory $DIR does not contain package $PACKAGE"
+    return 1
   fi
 }
 
@@ -117,13 +188,19 @@ VERBOSE=0
 
 while [[ "$1" == -* ]]; do
   case "$1" in
-  -d|--dir)
+  -d)
     shift
     DIR="$1"
     ;;
-  -t|--target)
+  --dir=*)
+    DIR="${1#*=}"
+    ;;
+  -t)
     shift
     TARGET="$1"
+    ;;
+  --target=*)
+    TARGET="${1#*=}"
     ;;
   -S|--stow)
     shift
@@ -137,17 +214,14 @@ while [[ "$1" == -* ]]; do
     shift
     restow "$1" "$DIR" "$TARGET" "$IGNORE" "$DEFER" "$OVERRIDE" "$ADOPT" "$DOTFILES" "$COMPAT" "$SIMULATE" "$VERBOSE"
     ;;
-  --ignore)
-    shift
-    IGNORE="$1"
+  --ignore=*)
+    IGNORE="${1#*=}"
     ;;
-  --defer)
-    shift
-    DEFER="$1"
+  --defer=*)
+    DEFER="${1#*=}"
     ;;
   --override)
-    shift
-    OVERRIDE="$1"
+    OVERRIDE="${1#*=}"
     ;;
   --adopt)
     ADOPT=1
@@ -164,9 +238,8 @@ while [[ "$1" == -* ]]; do
   -v*)
     (( VERBOSE += ${#1} - 2 ))
     ;;
-  --verbose)
-    shift
-    VERBOSE="$1"
+  --verbose=*)
+    VERBOSE="${1#*=}"
     ;;
   -h|--help)
     help
